//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPCoffee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeEntities1 : DbContext
    {
        public CoffeeEntities1()
            : base("name=CoffeeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Coffee> Coffee { get; set; }
        public virtual DbSet<PhotoDetails> PhotoDetails { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Constellation> Constellation { get; set; }
        public virtual DbSet<Continent> Continent { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Coupon> Coupon { get; set; }
        public virtual DbSet<CouponDetail> CouponDetail { get; set; }
        public virtual DbSet<IntroducePhotos> IntroducePhotos { get; set; }
        public virtual DbSet<Introduces> Introduces { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<MyLike> MyLike { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStates> OrderStates { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<Qquestionnaire> Qquestionnaire { get; set; }
        public virtual DbSet<Roasting> Roasting { get; set; }
        public virtual DbSet<ShoppingCar> ShoppingCar { get; set; }
        public virtual DbSet<ShoppingCarDetail> ShoppingCarDetail { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
