//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffee
    {
        public int CoffeeID { get; set; }
        public int ProductID { get; set; }
        public string CoffeeName { get; set; }
        public int CountryID { get; set; }
        public int RoastingID { get; set; }
        public int ProcessID { get; set; }
        public int PackageID { get; set; }
        public Nullable<int> ConstellationID { get; set; }
        public bool RainForest { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Constellation Constellation { get; set; }
        public virtual Country Country { get; set; }
        public virtual Package Package { get; set; }
        public virtual Process Process { get; set; }
        public virtual Roasting Roasting { get; set; }
    }
}
